# Generated by Django 5.1.7 on 2025-03-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField()),
                ('data_type', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('cancer_type', models.CharField(max_length=255)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
