"""
Django settings for sun_protection project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/

"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# API Keys - now loaded from .env file with no hardcoded fallbacks
API_KEY = os.getenv("API_KEY")
UV_API_URL = "https://api.weatherapi.com/v1/current.json"

MAPBOX_API_KEY = os.getenv("MAPBOX_API_KEY")
MAPBOX_GEOCODING_URL = "https://api.mapbox.com/geocoding/v5/mapbox.places"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#OLD SECURITY KEY
# SECRET_KEY = 'django-insecure-0le$@@hnittt4dajbl(fs34y6-h8kf%lqi1ji!8bn%iz0f-(w^'
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Load debug mode from environment variables (Default: False)
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"

# Set ALLOWED_HOSTS based on the environment
if DEBUG:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]  # Local development
else:
    ALLOWED_HOSTS = ["skinprotection.me"]  # Production domain


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'uv_tracker',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'uv_tracker/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sun_protection.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'uv_tracker/static'),
]

# STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security settings
if DEBUG:
    # Development: Disable HTTPS-only settings for localhost testing
    SECURE_REFERRER_POLICY = "no-referrer-when-downgrade"
    SESSION_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_HTTPONLY = False
    CSRF_COOKIE_HTTPONLY = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SECURE_PROXY_SSL_HEADER = None

    CSP_IMG_SRC = ("'self'", "data:", "http://127.0.0.1:8000/static/")  
    CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "http://127.0.0.1:8000/static/", "https://skinprotection.me/static/")  
    CSP_FONT_SRC = ("'self'", "http://127.0.0.1:8000/static/")
else:
    # Production: Enforce strict security settings
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
    SESSION_COOKIE_SAMESITE = "Strict" # Prevents CSRF attacks via third-party sites
    SESSION_COOKIE_HTTPONLY = True # Prevents JavaScript from accessing session cookies
    CSRF_COOKIE_HTTPONLY = True # Protects CSRF token from JavaScript
    SESSION_COOKIE_SECURE = True  # Enforce HTTPS for session cookies
    CSRF_COOKIE_SECURE = True # Enforce HTTPS for CSRF token
    SECURE_SSL_REDIRECT = True  # Enforce HTTPS
    SECURE_HSTS_SECONDS = 31536000  # Enable HSTS (1 year)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Required for reverse proxies

    CSP_IMG_SRC = ("'self'", "data:", "https://skinprotection.me/static/")
    CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://skinprotection.me/static/", "https://fonts.googleapis.com")
    CSP_FONT_SRC = ("'self'", "https://skinprotection.me/static/")
 
# Global CSP Settings
ROOT_URLCONF = 'sun_protection.urls'
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'") # POTENTIALLY UNSAFE!
CSP_CONNECT_SRC = ("'self'", "https://api.mapbox.com", "https://api.weatherapi.com")